org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# React Native New Architecture
newArchEnabled=false
# Use Hermes engine
hermesEnabled=false

expo.useLegacyPackaging=true
compileSdkVersion=34
targetSdkVersion=34
minSdkVersion=23
buildToolsVersion=34.0.0
